Apply a guard only on ios
tonlabs/UIKit pull request #1225
Opened 2021-08-23 16:22 UTC by savelichalex

2021-08-23 18:26 UTC, sertony requested changes
Consider changing the base into `surf@6.3.0` if it's a bug to fix for beta

2021-08-23 18:26 UTC, sertony commented on packages/navigation/src/UILargeTitleHeader/useOnScrollHandler/onScroll.native.tsx
> +        if (isIOS && !ctx != null && !ctx.scrollTouchGuard) {
Maybe you wanted to do this? I'm not sure why have you added the leading `!` to `ctx != null` condition...
```suggestion
        if (isIOS && ctx != null && !ctx.scrollTouchGuard) {
```

2021-08-23 18:27 UTC, sertony commented
Btw, what bug does it fix?

2021-08-23 18:58 UTC, savelichalex commented
> Btw, what bug does it fix?

So this fix is not needed on Android, but it brakes normal behaviour, as we call `onScroll` without passing a context from a gesture handler (and we can't get this context, moreover we shouldn't)

2021-08-24 08:14 UTC, sertony approved these changes

2021-08-24 08:16 UTC, SAnatoliiS approved these changes

2021-08-24 08:26 UTC, sertony approved these changes

2021-08-24 08:26 UTC, merged