Lokalise: Translations update
tonlabs/UIKit pull request #1398
Opened 2021-12-10 06:13 UTC by localized26

This pull request was initiated by Lokalise (user Khesha Tsyrenova) at 2021-12-10 07:13:39

2021-12-10 06:19 UTC, kkkhesha requested changes

2021-12-10 06:19 UTC, kkkhesha commented on localization/src/languages/ko.json
> +    "AtTime": "at",
```suggestion
    "AtTime": "",
```

2021-12-10 06:19 UTC, kkkhesha commented on localization/src/languages/ko.json
>      "Apartment": "Apartment/Suite/Unit",
остается на английском пока

2021-12-10 06:19 UTC, kkkhesha commented on localization/src/languages/ko.json
> +        "Title": "Choose a Country"
```suggestion
        "Title": "국가 선택"
```

2021-12-10 06:20 UTC, kkkhesha approved these changes

2021-12-10 11:39 UTC, sertony approved these changes

2021-12-14 08:20 UTC, savelichalex approved these changes

2021-12-14 08:20 UTC, merged