Lokalise: Translations update
tonlabs/UIKit pull request #1488
Opened 2022-02-03 08:11 UTC by localized26

This pull request was initiated by Lokalise (user Khesha Tsyrenova) at 2022-02-03 09:11:00

2022-02-03 08:13 UTC, kkkhesha commented on localization/src/languages/ko.json
> +    "AtTime": "at",
```suggestion
    "AtTime": "",
```

2022-02-03 08:13 UTC, kkkhesha commented on localization/src/languages/ko.json
>      "Was": "was",
```suggestion
    "Was": "",
```

2022-02-03 08:15 UTC, kkkhesha requested changes
@BigRoma @sertony сделала новый пир, проверьте плиз. Две замены на английском удалила, поэтому отправляю на request changes

2022-02-03 08:23 UTC, sertony approved these changes

2022-02-03 08:23 UTC, merged

2022-02-04 06:17 UTC, kkkhesha commented
@BigRoma ping