Pass onClose if it's needed for a modal route
tonlabs/UIKit pull request #1652
Opened 2022-07-15 13:10 UTC by savelichalex

2022-07-21 07:40 UTC, SAnatoliiS approved these changes

2022-07-21 14:04 UTC, BigRoma requested changes

2022-07-21 14:04 UTC, BigRoma commented on casts/modalNavigator/src/ModalNavigator/createModalNavigator.tsx
> +            onClose={'onClose' in route ? route.onClose : hide}
It's too much. What I must do if I need only handle event but need close modal anyway?
Suggest transfer onClose event to hide function.

2022-10-26 14:30 UTC, sertony approved these changes

2022-10-26 14:30 UTC, merged