Add ever links package
tonlabs/UIKit pull request #1674
Opened 2022-09-12 07:33 UTC by vetkamak

2022-09-12 07:35 UTC, vetkamak commented on localization/src/languages/ko.json
> +    },
@kkkhesha could you add korean translations here, pls?

2022-09-12 07:37 UTC, vetkamak commented on localization/src/languages/ru.json
> +    },
@kkkhesha and also make translations here

2022-09-12 08:47 UTC, sertony approved these changes

2022-09-12 09:08 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "Amount": "Amount",
```suggestion
            "Amount": "총액",
```

2022-09-12 09:09 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "ActionTitle": "Send tokens",
```suggestion
            "ActionTitle": "토큰 보내기",
```

2022-09-12 09:10 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "Confirm": "Confirm",
```suggestion
            "Confirm": "확인",
```

2022-09-12 09:11 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "NetworkFee": "Network fee",
```suggestion
            "NetworkFee": "네트워크 수수료",
```

2022-09-12 09:11 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "RecipientAddress": "Recipient’s address",
```suggestion
            "RecipientAddress": "수신자 주소",
```

2022-09-12 09:13 UTC, kkkhesha commented on localization/src/languages/ko.json
> +            "Title": "Confirm external action"
```suggestion
            "Title": "외부 행동 확인"
```

2022-09-12 09:15 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "Amount": "Amount",
```suggestion
            "Amount": "Сумма",
```

2022-09-12 09:16 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "ActionTitle": "Send tokens",
```suggestion
            "ActionTitle": "Отправить токены",
```

2022-09-12 09:16 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "Confirm": "Confirm",
```suggestion
            "Confirm": "Подтвердить",
```

2022-09-12 09:17 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "NetworkFee": "Network fee",
```suggestion
            "NetworkFee": "Комиссия сети",
```

2022-09-12 09:17 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "RecipientAddress": "Recipient’s address",
```suggestion
            "RecipientAddress": "Адрес получателя",
```

2022-09-12 09:22 UTC, kkkhesha commented on localization/src/languages/ru.json
> +            "Title": "Confirm external action"
```suggestion
            "Title": "Подтвердить внешнюю операцию"
```

2022-09-12 09:22 UTC, SAnatoliiS requested changes

2022-09-12 09:22 UTC, SAnatoliiS commented on Example/package.json
> +        "@tonlabs/uistory.ever-links": "*",
It is necessary to add an example of using new components to the Example.

2022-09-12 09:22 UTC, SAnatoliiS commented on stories/everLinks/src/SendSheet.tsx
> +import { UIConstant, UIStyle } from '@tonlabs/uikit.core';
We are getting rid of legacy packages. For layout tasks, use UILayoutConstant from `@tonlabs/uikit.layout`

2022-09-13 14:48 UTC, sertony approved these changes

2022-09-13 14:56 UTC, SAnatoliiS commented on Example/src/screens/EverLinks.tsx
> +export function EverLinksScreen() {
This is redundant. This was made by `Split.Screen`. Consider to remove `ExampleScreen` and `ExampleSection`.

2022-09-14 07:00 UTC, SAnatoliiS approved these changes

2022-09-14 08:29 UTC, sertony approved these changes

2022-09-14 08:29 UTC, merged